config/routes.rb
Rails.application.routes.draw do
  get "question_categories/show"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :article_categories do
    resources :articles do
      resources :replies
      resources :likes, only: [:create, :destroy]
    end
  end

  resources :question_categories do
    resources :questions do
      resources :answers do
        resources :comments, only: [:create, :destroy]
        resources :votes, only: [:create, :destroy]
      end
    end
  end

  resources :sessions, only: [:create]
  resources :questions do
    resources :answers do
      resources :comments, only: [:create, :destroy]
      resources :votes, only: [:create, :destroy]
    end
  end

  resources :answers do
    resources :comments, only: [:create, :destroy]
    resources :votes, only: [:create, :destroy]
  end

  resources :votes, only: [:destroy]
  resources :comments, only: [:destroy]

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :articles do
    resources :replies
    resources :likes, only: [:create, :destroy]
  end

  resources :likes, only: [:create, :destroy]

  resources :relationships, only: [:create, :destroy]
  resources :user_article_relationships, only: [:create, :destroy]
  resources :user_question_relations, only: [:create, :destroy]
  delete :logout, to: "sessions#logout"
  get :logged_in, to: "sessions#logged_in"
  root to: "static#index"

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :article_categories do
        resources :articles do
          resources :replies
          resources :likes, only: [:create, :destroy]
        end
      end

      resources :question_categories do
        resources :questions do
          resources :answers do
            resources :comments, only: [:create, :destroy]
            resources :votes, only: [:create, :destroy]
          end
        end
      end
      resources :sessions, only: [:create]
      resources :questions do
        resources :answers do
          resources :comments
          resources :votes, only: [:create, :destroy]
        end
      end

      resources :answers do
        resources :comments
        resources :votes, only: [:create, :destroy]
      end

      resources :users do
        member do
          get :following, :followers
        end
      end

      resources :articles do
        resources :replies
        resources :likes, only: [:create, :destroy]
      end
      resources :registrations, only: [:create]
      resources :relationships, only: [:create, :destroy]
      resources :user_article_relationships, only: [:create, :destroy]
      resources :user_question_relations, only: [:create, :destroy]
      delete :logout, to: "sessions#logout"
      get :logged_in, to: "sessions#logged_in"
      root to: "static#home"
    end
  end
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :replies, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :user
  belongs_to :article_category

  def liked_by?(user)
    likes.exists?(user_id: user.id)
  end
end

app/controllers/api/v1/articles_controller.rb
module Api
  module V1
    class ArticlesController < ApplicationController
      before_action :set_article, only: [:show]

      def index
        @art = []
        current_user = User.find(session[:user_id])
        if current_user
          @articles = Article.where(article_category_id: current_user.articles_subscribed).order(created_at: :desc)
          @articles.each do |article|
            @user = User.find(article.user_id)
            @category = ArticleCategory.find(article.article_category_id)
            @art.push({ id: article.id, title: article.title, publisher: @user.name, image: article.image, date: article.created_at, category: @category.name })
          end
          render json: @art
        else
          @articles = Article.all.order(created_at: :desc)
          render json: @articles
        end
      end

      def show
        @replys = []
        @article.replies.each do |reply|
          @user = User.find(reply.user_id)
          @replys.push({ id: reply.id, user: @user.email, reply: reply.title, created: reply.created_at })
        end
        render json: { article: @article, replies: @replys, likes: @article.likes.count }
      end

      private

      def set_article
        @article = Article.find(params[:id])
      end

      def articles_params
        params.require(:article).permit(:title, :link, :image)
      end
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    # select by articles by category user is following
    if @current_user
      @articles = Article.where(article_category_id: @current_user.articles_subscribed).order(created_at: :desc)
    else
      @articles = Article.all.order(created_at: :desc)
    end
    @categories = ArticleCategory.all
  end

  def show
    @replys = []
    @article.replies.each do |reply|
      @user = User.find(reply.user_id)
      @replys.push({ id: reply.id, user: @user.email, reply: reply.title, created: reply.created_at })
    end
  end

  def new
    @article = Article.new
    @url = params[:search]
    if @url
      @myarticles = []
      doc = Nokogiri::HTML(URI.open(@url).read)
      @title = doc.css(".entry-title").text
      @image = doc.css("img").attr("src") ? doc.css("img.wp-post-image").attr("src").value : doc.css("img.wp-post-image").attr("src")
      @link = @url
    end
  end

  def create
    current_user = User.find(session[:user_id])
    @article = current_user.articles.build(articles_params)
    if @article.save
      redirect_to articles_path
      flash[:success] = "Article created"
    else
      flash[:error] = "Error creating article"
      render :new
    end
  end

  def edit
  end

  # edit the article
  def update
    if @article.update(articles_params)
      redirect_to @article
    else
      render edit
    end
  end

  def destroy
    if @article.destroy
      redirect_to articles_path
    else
      render json: { status: "Error destroying the post" }
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def articles_params
    params.require(:article).permit(:title, :link, :image, :article_category_id)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  require "redcarpet/render_strip"

  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(:filter_html => true, :hard_wrap => true)
    options = {
      fenced_code_blocks: true,
      no_intra_emphasis: true,
      autolink: true,
      lax_html_blocks: true,
    }
    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end

  def strip_markdown(text)
    markdown_to_plain_text = Redcarpet::Markdown.new(Redcarpet::Render::StripDown)
    markdown_to_plain_text.render(text).html_safe
  end
end

app/views/articles/_follow.html.erb
<%= button_tag type: 'submit', class: "btn btn-icon text-success", title: "Follow" do %>
  follow
<% end %>

app/views/articles/_unfollow.html.erb
<%= button_tag type: 'submit', class: "btn text-danger btn-icon", title: "UnFollow" do %>
  unfollow
<% end %>

app/views/articles/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('articles/unfollow')) %>");

app/views/articles/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('articles/follow')) %>");

app/views/articles/index.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <h1>Latest News</h1>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <div class="col-md-8 col-xl-9 middle-wrapper">
        <div class="row">
          <% @articles.each do |article| %>
            <div class="col-lg-4 col-sm-12 mb-4">
              <div class="card">
                <%= link_to article.link, target: "_blank" do %><img src="<%= article.image %>" class="card-img-top" width="100%" height="225"><% end %>
                <div class="card-body news-card">
                  <h6 class="card-title"><%= link_to article.link, target: "_blank" do %><%= truncate(strip_markdown(article.title), length: 40) %><% end %></h6>
                  <p class="card-text">
                    <small class="text-muted">
                      <%= article.user.name ? article.user.name : article.user.email %> | 
                      <%= article.created_at.strftime("%d %b %Y") %> | 
                      Likes <%= article.likes.count %>
                    </small>
                    <% if @current_user %>
                      <% if article.liked_by?(@current_user) %>
                        <%= button_to like_path(article.likes.find_by(user_id: @current_user.id)), method: :delete, class: "btn btn-outline-danger m-1" do %>
                          <i class="fa fa-thumbs-o-down"></i>
                        <% end %>
                      <% else %>
                        <%= button_to article_likes_path(article), method: "post", class: "btn btn-outline-success" do %>
                          <i class="fa fa-thumbs-o-up"></i>
                        <% end %>
                      <% end %>
                    <% end %>
                  </p>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <!-- right wrapper start -->
      <div class="d-none d-xl-block col-xl-3 right-wrapper">
        <div class="row">
          <div class="col-md-12 grid-margin">
            <div class="card rounded">
              <div class="card-body">
                <h6 class="card-title">Categories</h6>
                <% @categories.each do |category| %>
                  <div class="d-flex justify-content-between mb-2 pb-2 border-bottom">
                    <div class="d-flex align-items-center hover-pointer">
                      <img class="img-xs rounded-circle" src="https://bootdey.com/img/Content/avatar/avatar2.png" alt="">
                      <div class="ml-2">
                        <p><%= link_to category.name, category %></p>
                      </div>
                    </div>
                    <% if @current_user %>
                      <div id="follow_form">
                        <% if @current_user.subscribed_to_article?(category) %>
                          <%= form_with(model: @current_user.articles_following.find_by(followed_id: category.id),
             html: { method: :delete }, local: false) do |f| %>
                            <%= render "articles/unfollow"%>
                          <% end %>
                        <% else %>
                          <%= form_with(model: @current_user.articles_following.build, local: false) do |f| %>
                            <div><%= hidden_field_tag :followed_id, category.id %></div>
                            <%= render "articles/follow"%>
                          <% end %>
                        <% end %>
                      </div>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- right wrapper end -->
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<main class="container">
  <div class="row mb-2">
    <div class="col-md-8 mx-auto">
      <%= form_tag new_article_path, method: :get do %>
        <div class="form-group">
          <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: "Enter link to your blog post.." %>
        </div>
        <%= submit_tag "Get Article", class: "btn btn-outline-primary" %>
      <% end %>
    </div>
  </div>
</main>
<% if @url %>
  <div>
    <main class="container">
      <div class="row mb-2">
        <div class="col-md-8 mx-auto">
          <h1>Article</h1>
          <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
            <div class="col-8 p-4 d-flex flex-column position-static">
              <h3 class="mb-0"><%= link_to @title, @link %></h3>
              <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
              <%= form_for(@article) do |f| %>
                <%= f.hidden_field :title, value: @title %>
                <%= f.hidden_field :link, value: @link %>
                <%= f.hidden_field :image, value: @image %>
                <div class="form-group">
                  <%= f.label "Choose Category" %>
                  <%= f.select :article_category_id, ArticleCategory.all.map {|article_category| [article_category.name, article_category.id] }, class: "form-control" %>
                </div>
                <div class="form-actions">
                  <%= f.button :submit, value: "Add", class: "btn btn-success" %>
                </div>
              <% end %>
            </div>
            <div class="col-4 d-none d-lg-block">
              <%= image_tag @image, class: "img-responsive", height: "250" %>
            </div>
          </div>
        </div>
      </div>
    </main>
  </div>
<% end %>