config/routes.rb
Rails.application.routes.draw do
  get "question_categories/show"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :article_categories do
    resources :articles do
      resources :replies
      resources :likes, only: [:create, :destroy]
    end
  end

  resources :question_categories do
    resources :questions do
      resources :answers do
        resources :comments, only: [:create, :destroy]
        resources :votes, only: [:create, :destroy]
      end
    end
  end

  resources :sessions, only: [:create]
  resources :questions do
    resources :answers do
      resources :comments, only: [:create, :destroy]
      resources :votes, only: [:create, :destroy]
    end
  end

  resources :answers do
    resources :comments, only: [:create, :destroy]
    resources :votes, only: [:create, :destroy]
  end

  resources :votes, only: [:destroy]
  resources :comments, only: [:destroy]

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :articles do
    resources :replies
    resources :likes, only: [:create, :destroy]
  end

  resources :likes, only: [:create, :destroy]

  resources :relationships, only: [:create, :destroy]
  resources :user_article_relationships, only: [:create, :destroy]
  resources :user_question_relations, only: [:create, :destroy]
  delete :logout, to: "sessions#logout"
  get :logged_in, to: "sessions#logged_in"
  root to: "static#index"

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :article_categories do
        resources :articles do
          resources :replies
          resources :likes, only: [:create, :destroy]
        end
      end

      resources :question_categories do
        resources :questions do
          resources :answers do
            resources :comments, only: [:create, :destroy]
            resources :votes, only: [:create, :destroy]
          end
        end
      end
      resources :sessions, only: [:create]
      resources :questions do
        resources :answers do
          resources :comments
          resources :votes, only: [:create, :destroy]
        end
      end

      resources :answers do
        resources :comments
        resources :votes, only: [:create, :destroy]
      end

      resources :users do
        member do
          get :following, :followers
        end
      end

      resources :articles do
        resources :replies
        resources :likes, only: [:create, :destroy]
      end
      resources :registrations, only: [:create]
      resources :relationships, only: [:create, :destroy]
      resources :user_article_relationships, only: [:create, :destroy]
      resources :user_question_relations, only: [:create, :destroy]
      delete :logout, to: "sessions#logout"
      get :logged_in, to: "sessions#logged_in"
      root to: "static#home"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :questions
  has_many :answers, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :articles, dependent: :destroy
  has_many :replies, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :likes, dependent: :destroy
  #users following each other
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                                   foreign_key: "followed_id",
                                   dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  #users following article categories
  has_many :articles_following, class_name: "UserArticleRelationship",
                                foreign_key: "follower_id",
                                dependent: :destroy
  has_many :articles_subscribed, through: :articles_following, source: :followed

  #users following question categories
  has_many :questions_following, class_name: "UserQuestionRelation",
                                 foreign_key: "follower_id",
                                 dependent: :destroy
  has_many :questions_subscribed, through: :questions_following, source: :followed

  has_secure_password

  validates_presence_of :email
  validates_uniqueness_of :email

  def follow(other_user)
    following << other_user unless self == other_user
  end

  def follow_articles(article_category)
    articles_subscribed << article_category unless self == article_category
  end

  def follow_questions(question_category)
    questions_subscribed << question_category unless self == question_category
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def unsubscribe_article(article_category)
    articles_subscribed.delete(article_category)
  end

  def unsubscribe_question(question_category)
    questions_subscribed.delete(question_category)
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def subscribed_to_article?(article_category)
    articles_subscribed.include?(article_category)
  end

  def subscribed_to_question?(question_category)
    questions_subscribed.include?(question_category)
  end

  # Returns a user's feed.
  def feed
    part_of_feed = "relationships.follower_id = :id or answers.user_id = :id"
    Answer.left_outer_joins(user: :followers)
      .where(part_of_feed, { id: id }).distinct.order(created_at: :desc)
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < ApplicationController
      def show
        @user = User.find(session[:user_id])
        @articles = @user.articles
        @following = @user.following.count
        @followers = @user.followers.count
        render json: { user: @user, articles: @articles, following: @following, followers: @followers, feed: @user.feed }
      end

      def following
        @title = "Following"
        @user = User.find(session[:user_id])
        @users = @user.following
        render json: @users
      end

      def followers
        @title = "Followers"
        @user = User.find(session[:user_id])
        @users = @user.followers
        render json: @users
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include CurrentUserConcern

  before_action :set_user, only: [:edit, :destroy, :update, :show]
  before_action :authenticate_user, except: [:new, :edit, :create, :update, :destroy]

  def show
    @user = User.find(params[:id])
    @articles = @user.articles.order(created_at: :desc)
    @following = @user.following
    @followers = @user.followers
    @users = User.order("RANDOM()").limit(5)
    @answers = @user.answers.order(created_at: :desc)
    @article_categories = ArticleCategory.all.order(created_at: :desc)
    @question_categories = QuestionCategory.all.order(created_at: :desc)
  end

  def following
    @user = User.find(params[:id])
    @users = @user.following
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
      flash[:success] = "Thank you for signing up!"
    else
      render new
    end
  end

  def update
    if @user.update(user_profile)
      redirect_to @user
      flash[:success] = "User updated!"
    else
      flash[:error] = "Failed to update"
    end
  end

  def destroy
    if @user.destroy
      redirect_to new_user_path
      reset_session
      flash[:success] = "Your account has been successfully destroyed"
    else
      flash[:error] = "Error deleting your account"
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def user_profile
    params.require(:user).permit(:name, :email, :image, :bio, :birth)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_answers.html.erb
  <% @answers.each do |answer|%>
  <div class="col-md-12 grid-margin">
    <div class="card rounded">
      <div class="card-header">
        <div class="d-flex align-items-center justify-content-between">
          <div class="d-flex align-items-center">
            <img class="img-xs rounded-circle" src="https://bootdey.com/img/Content/avatar/avatar6.png" alt="">
            <div class="ml-2">
              <p><%= answer.user.name ? answer.user.name : answer.user.email %></p>
              <p class="tx-11 text-muted"><%= time_ago_in_words(answer.created_at) %> ago </p>
            </div>
          </div>
        </div>
      </div>
      <div class="card-body">
        <p class="mb-3 tx-14">
          <%= link_to answer do %>
            <strong><%= answer.question.title if answer.question %>?</strong>
          <% end %>
        </p>
        <p class="mb-3 tx-14"><%= answer.title %></p>
      </div>
      <div class="card-footer">
        <div class="d-flex post-actions">
          <% if answer.voted_by?(@current_user) %>
            <%= button_to answer_votes_path(answer), method: "post", disabled: true, class: "btn btn-outline-secondary" do %>
              <i class="fa fa-thumbs-o-up"></i>
            <% end %>
            <%= button_to vote_path(answer.votes.find_by(user_id: @current_user.id)), method: :delete, class: "btn btn-outline-danger m-1" do %>
              <i class="fa fa-thumbs-o-down"></i>
            <% end %>
          <% else %>
            <%= button_to answer_votes_path(answer), method: "post", class: "btn btn-outline-success" do %>
              <i class="fa fa-thumbs-o-up"></i>
            <% end %>
          <% end %>
          <p class="d-none d-md-block ml-2">Votes <%= answer.votes.count %></p>

          <%= link_to answer, class:"d-flex align-items-center text-muted mr-4" do %>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-message-square icon-md">
              <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path>
            </svg>
            <p class="d-none d-md-block ml-2">Comment <%= answer.comments.count %></p>
          <% end %>
          <a href="javascript:;" class="d-flex align-items-center text-muted">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-share icon-md">
              <path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8"></path>
              <polyline points="16 6 12 2 8 6"></polyline>
              <line x1="12" y1="2" x2="12" y2="15"></line>
            </svg>
            <p class="d-none d-md-block ml-2">Share</p>
          </a>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_followers.html.erb
  <% @user.followers.each do |follower|%>
  <div class="col-md-12 grid-margin">
    <div class="card rounded">
      <div class="card-header">
        <div class="d-flex align-items-center justify-content-between">
          <div class="d-flex align-items-center">
            <% if follower.image? %>
              <%= image_tag follower.image_url, class: "img-responsive", height: "50", alt: "profile pic" %>
            <% else %>
              <img class="img-xs rounded-circle" src="https://bootdey.com/img/Content/avatar/avatar2.png" alt="">
            <% end %>
            <div class="ml-2">
              <p><%= link_to follower do %><%= follower.name ? follower.name : follower.email %><% end %></p>
            </div>
            <div id="follow_form">
              <% if @current_user.following?(follower) %>
                <%= form_with(model: @current_user.active_relationships.find_by(followed_id: follower.id), html: { method: :delete }, local: true) do |f| %>
                  <%= button_tag type: 'submit', class: "btn text-danger btn-icon", title: "UnFollow" do %>
                    unfollow
                  <% end %>
                <% end %>
              <% else %>
                <%= form_with(model: @current_user.active_relationships.build, local: true) do |f| %>
                  <div><%= hidden_field_tag :followed_id, follower.id %></div>
                  <%= button_tag type: 'submit', class: "btn btn-icon text-success", title: "Follow" do %>
                    follow
                  <% end %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_following.html.erb
  <% @user.following.each do |following|%>
  <div class="col-md-12 grid-margin">
    <div class="card rounded">
      <div class="card-header">
        <div class="d-flex align-items-center justify-content-between">
          <div class="d-flex align-items-center">
            <% if following.image? %>
              <%= image_tag following.image_url, class: "img-responsive", height: "50", alt: "profile pic" %>
            <% else %>
              <img class="img-xs rounded-circle" src="https://bootdey.com/img/Content/avatar/avatar2.png" alt="">
            <% end %>
            <div class="ml-2">
              <p><%= link_to following do %><%= following.name ? following.name : following.email %><% end %></p>
            </div>
            <div id="follow_form">
              <% if @current_user.following?(following) %>
                <%= form_with(model: @current_user.active_relationships.find_by(followed_id: following.id), html: { method: :delete }, local: true) do |f| %>
                  <%= button_tag type: 'submit', class: "btn text-danger btn-icon", title: "UnFollow" do %>
                    unfollow
                  <% end %>
                <% end %>
              <% else %>
                <%= form_with(model: @current_user.active_relationships.build, local: true) do |f| %>
                  <div><%= hidden_field_tag :followed_id, following.id %></div>
                  <%= button_tag type: 'submit', class: "btn btn-icon text-success", title: "Follow" do %>
                    follow
                  <% end %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_info.html.erb
<div class="card-body">
  <div class="mt-3">
    <label class="tx-11 font-weight-bold mb-0 text-uppercase">Name:</label>
    <p class="text-muted"><%= @user.name ? @user.name : @user.email %></p>
  </div>
  <% if @current_user.id == @user.id %>
    <div class="mt-3">
      <label class="tx-11 font-weight-bold mb-0 text-uppercase">Email:</label>
      <p class="text-muted"><%= @user.email %></p>
    </div>
    <div class="mt-3">
      <label class="tx-11 font-weight-bold mb-0 text-uppercase">Birthdate:</label>
      <p class="text-muted"><%= @user.birth %></p>
    </div>
  <% end %>
  <div class="mt-3">
    <label class="tx-11 font-weight-bold mb-0 text-uppercase">Bio:</label>
    <p class="text-muted"><%= @user.bio %></p>
  </div>
</div>

app/views/users/_right-wrapper.html.erb
<div class="d-none d-xl-block col-xl-3 right-wrapper">
  <div class="row">
    <div class="col-md-12 grid-margin">
      <div class="card rounded">
        <div class="card-body">
          <h6 class="card-title">Follow Users</h6>
          <% @users.each do |user|%>
            <% if !@current_user.following?(user) %>
              <div class="d-flex justify-content-between mb-2 pb-2 border-bottom">
                <div class="d-flex align-items-center hover-pointer">
                  <% if user.image? %>
                    <%= image_tag user.image_url, class: "img-responsive", height: "50", alt: "profile pic" %>
                  <% else %>
                    <img class="img-xs rounded-circle" src="https://bootdey.com/img/Content/avatar/avatar2.png" alt="">
                  <% end %>
                  <div class="ml-2">
                    <p><%= link_to user do %><%= user.name ? user.name : user.email %><% end %></p>
                  </div>
                </div>
                <div id="follow_form">
                  <% if @current_user.following?(user) %>
                    <%= form_with(model: @current_user.active_relationships.find_by(followed_id: user.id), html: { method: :delete }, local: true) do |f| %>
                      <%= button_tag type: 'submit', class: "btn text-danger btn-icon", title: "UnFollow" do %>
                        unfollow
                      <% end %>
                    <% end %>
                  <% else %>
                    <%= form_with(model: @current_user.active_relationships.build, local: true) do |f| %>
                      <div><%= hidden_field_tag :followed_id, user.id %></div>
                      <%= button_tag type: 'submit', class: "btn btn-icon text-success", title: "Follow" do %>
                        follow
                      <% end %>
                    <% end %>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-12 grid-margin">
      <div class="card rounded">
        <div class="card-body">
          <h6 class="card-title">Follow Article Topics</h6>
          <% @article_categories.each do |acategory| %>
            <div class="d-flex justify-content-between mb-2 pb-2 border-bottom">
              <div class="d-flex align-items-center hover-pointer">
                <div class="ml-2">
                  <p><%= link_to acategory.name, acategory %></p>
                </div>
              </div>
              <% if @current_user %>
                <div id="follow_form">
                  <% if @current_user.subscribed_to_article?(acategory) %>
                    <%= form_with(model: @current_user.articles_following.find_by(followed_id: acategory.id),
             html: { method: :delete }, local: false) do |f| %>
                      <%= render "articles/unfollow"%>
                    <% end %>
                  <% else %>
                    <%= form_with(model: @current_user.articles_following.build, local: false) do |f| %>
                      <div><%= hidden_field_tag :followed_id, acategory.id %></div>
                      <%= render "articles/follow"%>
                    <% end %>
                  <% end %>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-12 grid-margin">
      <div class="card rounded">
        <div class="card-body">
          <h6 class="card-title">Follow Question Topics</h6>
          <% @question_categories.each do |qcategory| %>
            <div class="d-flex justify-content-between mb-2 pb-2 border-bottom">
              <div class="d-flex align-items-center hover-pointer">
                <div class="ml-2">
                  <p><%= link_to qcategory.name, qcategory %></p>
                </div>
              </div>
              <% if @current_user %>
                <div id="follow_form">
                  <% if @current_user.subscribed_to_article?(qcategory) %>
                    <%= form_with(model: @current_user.articles_following.find_by(followed_id: qcategory.id),
             html: { method: :delete }, local: false) do |f| %>
                      <%= render "articles/unfollow"%>
                    <% end %>
                  <% else %>
                    <%= form_with(model: @current_user.articles_following.build, local: false) do |f| %>
                      <div><%= hidden_field_tag :followed_id, qcategory.id %></div>
                      <%= render "articles/follow"%>
                    <% end %>
                  <% end %>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_timeline.html.erb
  <% @user.feed.each do |answer|%>
  <div class="col-md-12 grid-margin">
    <div class="card rounded">
      <div class="card-header">
        <div class="d-flex align-items-center justify-content-between">
          <div class="d-flex align-items-center">
            <% if answer.user.image? %>
              <%= image_tag answer.user.image_url, class: "img-responsive", height: "60", alt: "profile pic" %>
            <% else %>
              <img class="img-xs rounded-circle" src="https://bootdey.com/img/Content/avatar/avatar2.png" alt="">
            <% end %>
            <div class="ml-2">
              <p><%= answer.user.name %></p>
              <p class="tx-11 text-muted"><%= time_ago_in_words(answer.created_at) %> ago</p>
            </div>
          </div>
        </div>
      </div>
      <%= link_to answer do %>
        <div class="card-body text-dark">
          <p class="mb-3 tx-14"><strong><%= answer.question.title if answer.question %>?</strong></p>
          <p class="mb-3 tx-14"><%= answer.title %></p>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1 class="py-3 text-center">Edit Profile</h1>
<div class="row justify-center my-2">
  <div class="col-md-3 col-md-offset-3 mx-auto">
    <%= button_to user_path(@user), method: :delete, class: "btn btn-danger btn-icon-text btn-edit-profile" do %>
      <i class="fa fa-trash"></i>
      <span class="">Delete Account</span>
    <% end %>
  </div>
  <div class="col-md-6 col-md-offset-3 mx-auto">
    <%= simple_form_for @user, html: {multipart:  true} do |f| %>
      <%= render 'shared/error_messages' %>
      <div class="form-group">
        <%= f.label "Profile Picture" %>
        <%= f.file_field :image, class: 'form-control', value: @user.image_url %>
      </div>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', value: @user.name %>
      </div>
      <div class="form-group">
        <%= f.label :birth %>
        <%= f.date_field :birth, class: 'form-control', value: @user.birth %>
      </div>
      <div class="form-group">
        <%= f.label :bio %>
        <%= f.text_area :bio, class: 'form-control', value: @user.bio %>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control', value: @user.email %>
      </div>
      <%= f.submit "Update", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="profile-page tx-13">
    <div class="row">
      <div class="col-12 grid-margin">
        <div class="profile-header">
          <div class="cover">
            <div class="gray-shade"></div>
            <div class="cover-body d-flex justify-content-between align-items-center">
              <div>
                <% if @user.image? %>
                  <%= image_tag @user.image_url, class: "img-responsive", height: "60", alt: "profile pic" %>
                <% else %>
                  <img class="img-xs rounded-circle" src="https://bootdey.com/img/Content/avatar/avatar2.png" alt="">
                <% end %>
                <span class="profile-name"><%= @user.name %></span>
                <% if @current_user != @user %>
                  <% if @current_user.following?(@user) %>
                    <%= form_with(model: @current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }, local: true) do |f| %>
                      <%= button_tag type: 'submit', class: "btn text-danger btn-icon", title: "UnFollow" do %>
                        unfollow
                      <% end %>
                    <% end %>
                  <% else %>
                    <%= form_with(model: @current_user.active_relationships.build, local: true) do |f| %>
                      <div><%= hidden_field_tag :followed_id, @user.id %></div>
                      <%= button_tag type: 'submit', class: "btn btn-icon text-success", title: "Follow" do %>
                        follow
                      <% end %>
                    <% end %>
                  <% end %>
                <% end %>
              </div>
              <div class="d-none d-md-block">
                <% if @current_user.id == @user.id %>
                  <%= link_to edit_user_path(@user), class: "btn btn-primary btn-icon-text btn-edit-profile" do %>
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit btn-icon-prepend">
                      <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path>
                      <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path>
                    </svg> Settings
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
          <div class="header-links">
            <ul class="links d-flex align-items-center mt-3 mt-md-0 nav nav-tabs" id="nav-tab" role="tablist">
              <li class="header-link-item d-flex align-items-center active" role="presentation">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-columns mr-1 icon-md">
                  <path d="M12 3h7a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-7m0-18H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h7m0-18v18"></path>
                </svg>
                <a class="pt-1px d-none d-md-block active" id="nav-timeline-tab" data-toggle="tab" href="#nav-timeline" role="tab" aria-controls="nav-timeline" aria-selected="true">Timeline</a>
              </li>
              <li class="header-link-item ml-3 pl-3 border-left d-flex align-items-center" role="presentation">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user mr-1 icon-md">
                  <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path>
                  <circle cx="12" cy="7" r="4"></circle>
                </svg>
                <a class="pt-1px d-none d-md-block" id="nav-following-tab" data-toggle="tab" href="#nav-following" role="tab" aria-controls="nav-following" aria-selected="false">Following <span class="text-muted tx-12"><%= @following.count %></span></a>
              </li>
              <li class="header-link-item ml-3 pl-3 border-left d-flex align-items-center" role="presentation">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users mr-1 icon-md">
                  <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
                  <circle cx="9" cy="7" r="4"></circle>
                  <path d="M23 21v-2a4 4 0 0 0-3-3.87"></path>
                  <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
                </svg>
                <a class="pt-1px d-none d-md-block" id="nav-followers-tab" data-toggle="tab" href="#nav-followers" role="tab" aria-controls="nav-followers" aria-selected="false">Followers <span class="text-muted tx-12"><%= @followers.count %></span></a>
              </li>
              <li class="header-link-item ml-3 pl-3 border-left d-flex align-items-center" role="presentation">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-columns mr-1 icon-md">
                  <path d="M12 3h7a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-7m0-18H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h7m0-18v18"></path>
                </svg>
                <a class="pt-1px d-none d-md-block" id="nav-answers-tab" data-toggle="tab" href="#nav-answers" role="tab" aria-controls="nav-answers" aria-selected="false">Answers <span class="text-muted tx-12"><%= @user.answers.count %></span></a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="row profile-body">
      <div class="d-none d-md-block col-md-4 col-xl-3 left-wrapper">
        <div class="card rounded">
          <%= render "users/info" %>
        </div>
      </div>
      <!-- middle wrapper start -->
      <div class="col-md-8 col-xl-6 middle-wrapper">
        <div class="tab-content" id="nav-tabContent">
          <div class="row tab-pane fade show active" id="nav-timeline" role="tabpanel" aria-labelledby="nav-timeline-tab">
            <h3>Posts</h3>
            <%= render "users/timeline"%>
          </div>
          <div class="row tab-pane fade" id="nav-following" role="tabpanel" aria-labelledby="nav-following-tab">
            <h3>Following</h3>
            <%= render "users/following"%>
          </div>
          <div class="row tab-pane fade" id="nav-followers" role="tabpanel" aria-labelledby="nav-followers-tab">
            <h3>Followers</h3>
            <%= render "users/followers"%>
          </div>
          <div class="row tab-pane fade" id="nav-answers" role="tabpanel" aria-labelledby="nav-answers-tab">
            <h3>My Answers</h3>
            <%= render "users/answers"%>
          </div>
        </div>
      </div>
      <!-- middle wrapper end -->
      <!-- right wrapper start -->
      <%= render "users/right-wrapper" %>
      <!-- right wrapper end -->
    </div>
  </div>
</div>