config/routes.rb
Rails.application.routes.draw do
  get "question_categories/show"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :article_categories do
    resources :articles do
      resources :replies
      resources :likes, only: [:create, :destroy]
    end
  end

  resources :question_categories do
    resources :questions do
      resources :answers do
        resources :comments, only: [:create, :destroy]
        resources :votes, only: [:create, :destroy]
      end
    end
  end

  resources :sessions, only: [:create]
  resources :questions do
    resources :answers do
      resources :comments, only: [:create, :destroy]
      resources :votes, only: [:create, :destroy]
    end
  end

  resources :answers do
    resources :comments, only: [:create, :destroy]
    resources :votes, only: [:create, :destroy]
  end

  resources :votes, only: [:destroy]
  resources :comments, only: [:destroy]

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :articles do
    resources :replies
    resources :likes, only: [:create, :destroy]
  end

  resources :likes, only: [:create, :destroy]

  resources :relationships, only: [:create, :destroy]
  resources :user_article_relationships, only: [:create, :destroy]
  resources :user_question_relations, only: [:create, :destroy]
  delete :logout, to: "sessions#logout"
  get :logged_in, to: "sessions#logged_in"
  root to: "static#index"

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :article_categories do
        resources :articles do
          resources :replies
          resources :likes, only: [:create, :destroy]
        end
      end

      resources :question_categories do
        resources :questions do
          resources :answers do
            resources :comments, only: [:create, :destroy]
            resources :votes, only: [:create, :destroy]
          end
        end
      end
      resources :sessions, only: [:create]
      resources :questions do
        resources :answers do
          resources :comments
          resources :votes, only: [:create, :destroy]
        end
      end

      resources :answers do
        resources :comments
        resources :votes, only: [:create, :destroy]
      end

      resources :users do
        member do
          get :following, :followers
        end
      end

      resources :articles do
        resources :replies
        resources :likes, only: [:create, :destroy]
      end
      resources :registrations, only: [:create]
      resources :relationships, only: [:create, :destroy]
      resources :user_article_relationships, only: [:create, :destroy]
      resources :user_question_relations, only: [:create, :destroy]
      delete :logout, to: "sessions#logout"
      get :logged_in, to: "sessions#logged_in"
      root to: "static#home"
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_rich_text :title

  def voted_by?(user)
    votes.exists?(user_id: user.id)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, except: [:show]

  #get answers from topics followed(question categories)
  def index
    @questions = Question.where(question_category_id: @current_user.questions_subscribed).order(created_at: :desc)
    @answers = Answer.where(question_id: @questions).order(created_at: :desc)
    @categories = QuestionCategory.all.order(created_at: :desc)
  end

  def show
    @answer = Answer.find(params[:id])
    @categories = QuestionCategory.all.order(created_at: :desc)
  end

  def create
    current_user = User.find(session[:user_id])
    @answer = current_user.answers.build(answers_params)
    @answer.question_id = params[:question_id]
    if @answer.save
      redirect_to @answer
      flash[:success] = "Answer created!"
    else
      flash[:error] = "Error creating answer"
    end
  end

  def edit
  end

  def update
    if @answer.update(answers_params)
      flash[:success] = "Answer updated!"
      redirect_to @answer
    else
      flash[:error] = "Error updating answer"
    end
  end

  def destroy
    if @answer.destroy
      flash.now[:success] = "Answer deleted!"
      redirect_to answers_path
    else
      flash[:error] = "Error destroying answer"
    end
  end

  private

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answers_params
    params.require(:answer).permit(:title)
  end
end

app/controllers/api/v1/answers_controller.rb
module Api
  module V1
    class AnswersController < ApplicationController
      before_action :set_answer, only: [:show, :edit, :update, :destroy]

      def index
        @answers = Answer.all.order(created_at: :desc)
        @allanswers = []
        @answers.each do |answer|
          @question = answer.question = Question.find(answer.question_id)
          @user = answer.user = User.find(answer.user_id)
          @allanswers.push({ id: answer.id, question: @question.title, answer: answer.title, created: answer.created_at, author: @user.email, comments: answer.comments.count, votes: answer.votes.count })
        end
        render json: @allanswers
      end

      def show
        @comment = []
        @answer.comments.each do |comment|
          comment.user = User.find(comment.user_id)
          @comment.push({ id: comment.id, user: comment.user.email, comment: comment.title, created: comment.created_at })
        end
        render json: { id: @answer.id, question: @answer.question.title, answer: @answer.title, created: @answer.created_at, author: @answer.user.email, votes: @answer.votes.count, comments: @comment }
      end

      def create
        @question = Question.find(params[:question_id])
        current_user = User.find(session[:user_id])
        @answer = current_user.answers.build(answers_params)
        @answer.question_id = @question.id
        if @answer.save
          render json: { status: "success", answer: @answer }
        else
          render json: { error: "Could not save answer" }
        end
      end

      def edit
      end

      def update
        if @answer.update(answer_params)
          render json: { status: "success" }
        else
          render json: { status: "error update the post" }
        end
      end

      def destroy
        if @answer.destroy
          render json: { status: "success" }
        else
          render json: { status: "error destroy the post" }
        end
      end

      private

      def set_answer
        @answer = Answer.find(params[:id])
      end

      def answers_params
        params.require(:answer).permit(:title)
      end
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_for([@question, @current_user.answers.build]) do |form| %>
  <div class="form-group">
    <%= form.label "Content" %>
    <%= form.rich_text_area :title %>
    <%= form.hidden_field :question_id, value: @question.id %>
  </div>
  <%= form.button :submit, class: "btn btn-primary"  %>
<% end %>

app/views/answers/_topics.html.erb
  <!-- right wrapper start -->
<div class="d-none d-xl-block col-xl-3 right-wrapper">
  <div class="row">
    <div class="col-md-12 grid-margin">
      <div class="card rounded">
        <div class="card-body">
          <h6 class="card-title">Categories</h6>
          <% @categories.each do |category| %>
            <div class="d-flex justify-content-between mb-2 pb-2 border-bottom">
              <div class="d-flex align-items-center hover-pointer">
                <div class="ml-2">
                  <p><%= link_to category.name, category %></p>
                </div>
              </div>
              <% if @current_user.subscribed_to_question?(category) %>
                <%= form_with(model: @current_user.questions_following.find_by(followed_id: category.id),
             html: { method: :delete }, local: true) do |f| %>
                  <%= button_tag type: 'submit', class: "btn text-danger btn-icon", title: "UnFollow" do %>
                    unfollow
                  <% end %>
                <% end %>
              <% else %>
                <%= form_with(model: @current_user.questions_following.build, local: true) do |f| %>
                  <div><%= hidden_field_tag :followed_id, category.id %></div>
                  <%= button_tag type: 'submit', class: "btn btn-icon text-success", title: "Follow" do %>
                    follow
                  <% end %>
                <% end %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- right wrapper end -->

app/views/answers/edit.html.erb
<%= form_for(@answer) do |form| %>
  <div class="form-group">
    <%= form.label "Content" %>
    <%= form.rich_text_area :title, value: @answer.title %>
  </div>
  <%= form.button :submit, class: "btn btn-primary"  %>
<% end %>

app/views/answers/index.html.erb
<div class="container">
  <div class="row profile-body">
    <!-- left wrapper start -->
    <div class="d-none d-md-block col-md-4 col-xl-3 left-wrapper">
      <div class="card rounded">
        <% if @current_user.image? %>
          <%= image_tag @current_user.image_url, class: "img-fluid", alt: "profile pic" %>
        <% else %>
          <img class="img-xs rounded-circle" src="https://bootdey.com/img/Content/avatar/avatar2.png" alt="">
        <% end %>
        <div class="card-body">
          <div class="mt-3">
            <label class="tx-11 font-weight-bold mb-0 text-uppercase">Name:</label>
            <p class="text-muted"><%= @current_user.name ? @current_user.name : @current_user.email %></p>
          </div>
          <div class="mt-3">
            <label class="tx-11 font-weight-bold mb-0 text-uppercase">Email:</label>
            <p class="text-muted"><%= @current_user.email %></p>
          </div>
          <div class="mt-3">
            <label class="tx-11 font-weight-bold mb-0 text-uppercase">Birthdate:</label>
            <p class="text-muted"><%= @current_user.birth %></p>
          </div>
          <div class="mt-3">
            <label class="tx-11 font-weight-bold mb-0 text-uppercase">Bio:</label>
            <p class="text-muted"><%= @current_user.bio %></p>
          </div>
        </div>
      </div>
    </div>
    <!-- left wrapper end -->
    <!-- middle wrapper start -->
    <div class="col-md-8 col-xl-6 middle-wrapper">
      <h1>Posts</h1>
      <hr>
      <div class="row">
        <% @answers.each do |answer|%>
          <div class="col-md-12 grid-margin">
            <div class="card rounded">
              <div class="card-header">
                <div class="d-flex align-items-center justify-content-between">
                  <div class="d-flex align-items-center">
                    <% if answer.user.image? %>
                      <%= image_tag answer.user.image_url, class: "img-responsive", height: "60", alt: "profile pic" %>
                    <% else %>
                      <img class="img-xs rounded-circle" src="https://bootdey.com/img/Content/avatar/avatar2.png" alt="">
                    <% end %>
                    <div class="ml-2">
                      <p><%= answer.user.name ? answer.user.name : answer.user.email %></p>
                      <p class="tx-11 text-muted"><%= time_ago_in_words(answer.created_at) %> ago </p>
                    </div>
                  </div>
                  <%# <div class="dropdown">
                    <button class="btn p-0" type="button" id="dropdownMenuButton2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-more-horizontal icon-lg pb-3px">
                        <circle cx="12" cy="12" r="1"></circle>
                        <circle cx="19" cy="12" r="1"></circle>
                        <circle cx="5" cy="12" r="1"></circle>
                      </svg>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton2">
                      <a class="dropdown-item d-flex align-items-center" href="#">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-meh icon-sm mr-2">
                          <circle cx="12" cy="12" r="10"></circle>
                          <line x1="8" y1="15" x2="16" y2="15"></line>
                          <line x1="9" y1="9" x2="9.01" y2="9"></line>
                          <line x1="15" y1="9" x2="15.01" y2="9"></line>
                        </svg> <span class="">Unfollow</span></a>
                      <a class="dropdown-item d-flex align-items-center" href="#">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-corner-right-up icon-sm mr-2">
                          <polyline points="10 9 15 4 20 9"></polyline>
                          <path d="M4 20h7a4 4 0 0 0 4-4V4"></path>
                        </svg> <span class="">Go to post</span></a>
                      <a class="dropdown-item d-flex align-items-center" href="#">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-share-2 icon-sm mr-2">
                          <circle cx="18" cy="5" r="3"></circle>
                          <circle cx="6" cy="12" r="3"></circle>
                          <circle cx="18" cy="19" r="3"></circle>
                          <line x1="8.59" y1="13.51" x2="15.42" y2="17.49"></line>
                          <line x1="15.41" y1="6.51" x2="8.59" y2="10.49"></line>
                        </svg> <span class="">Share</span></a>
                      <a class="dropdown-item d-flex align-items-center" href="#">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-copy icon-sm mr-2">
                          <rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
                          <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
                        </svg> <span class="">Copy link</span></a>
                    </div>
                  </div> %>
                </div>
              </div>
              <div class="card-body">
                <p class="mb-3 tx-14">
                  <%= link_to answer do %>
                    <strong><%= answer.question.title if answer.question %>?</strong>
                  <% end %>
                </p>
                <p class="mb-3 tx-14"><%= answer.title.to_plain_text.truncate(60) %></p>
              </div>
              <div class="card-footer">
                <div class="d-flex post-actions">
                  <p class="d-none d-md-block ml-2">
                    <% if answer.voted_by?(@current_user) %>
                      <%= button_to vote_path(answer.votes.find_by(user_id: @current_user.id)), method: :delete, class: "btn-outline-danger mr-1" do %>
                        <i class="fa fa-thumbs-o-down"></i>
                      <% end %>
                    <% else %>
                      <%= button_to answer_votes_path(answer), method: "post", class: "btn-outline-success mr-1" do %>
                        <i class="fa fa-thumbs-o-up"></i>
                      <% end %>
                    <% end %>
                    Votes <%= answer.votes.count %>
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-2 feather feather-message-square icon-md">
                      <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path>
                    </svg> Comments <%= answer.comments.count %></p>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <!-- middle wrapper end -->
    <%= render "answers/topics" %>
  </div>
</div>

app/views/answers/show.html.erb
<div class="container">
  <div class="row profile-body">
    <!-- middle wrapper start -->
    <div class="col-md-8 col-xl-8 middle-wrapper">
      <div class="row">
        <div class="col-md-12 grid-margin">
          <div class="card rounded">
            <div class="card-header">
              <div class="d-flex align-items-center justify-content-between">
                <div class="d-flex align-items-center">
                  <%= link_to @answer.user do %>
                    <% if  @answer.user.image? %>
                      <%= image_tag  @answer.user.image_url, class: "img-responsive", height: "60", alt: "profile pic" %>
                    <% else %>
                      <img class="img-xs rounded-circle" src="https://bootdey.com/img/Content/avatar/avatar2.png" alt="">
                    <% end %>
                  <% end %>
                  <div class="ml-2">
                    <p><%= link_to @answer.user.name ? @answer.user.name : @answer.user.email, @answer.user %></p>
                    <p class="tx-11 text-muted"><%= time_ago_in_words(@answer.created_at) %> ago </p>
                  </div>
                </div>
                <% if @current_user.id == @answer.user.id %>
                  <div class="dropdown">
                    <button class="btn p-0" type="button" id="dropdownMenuButton2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-more-horizontal icon-lg pb-3px">
                        <circle cx="12" cy="12" r="1"></circle>
                        <circle cx="19" cy="12" r="1"></circle>
                        <circle cx="5" cy="12" r="1"></circle>
                      </svg>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton2">
                      <%= link_to edit_answer_path(@answer), class: "dropdown-item d-flex align-items-center" do %>
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-corner-right-up icon-sm mr-2">
                          <polyline points="10 9 15 4 20 9"></polyline>
                          <path d="M4 20h7a4 4 0 0 0 4-4V4"></path>
                        </svg> <span class="">Edit</span>
                      <% end %>
                      <%= button_to answer_path(@answer), method: :delete, class: "dropdown-item d-flex align-items-center" do %>
                        <i class="fa fa-trash"></i>
                        <span class="">Delete</span>
                      <% end %>
                    </div>
                  </div>
                <% end %>
              </div>
              <div class="card-body">
                <p class="mb-3 tx-14"><strong><%= @answer.question.title  if @answer.question %>?</strong></p>
                <p class="mb-3 tx-14"><%= @answer.title %></p>
              </div>
              <div class="card-footer">
                <% if @current_user %>
                  <div class="d-flex post-actions">
                    <p class="pt-2 pl-2">
                      <% if @answer.voted_by?(@current_user) %>
                        <%= button_to vote_path(@answer.votes.find_by(user_id: @current_user.id)), method: :delete, class: "btn-outline-danger m-1" do %>
                          <i class="fa fa-thumbs-o-down"></i>
                        <% end %>
                      <% else %>
                        <%= button_to answer_votes_path(@answer), method: "post", class: "btn-outline-success" do %>
                          <i class="fa fa-thumbs-o-up"></i>
                        <% end %>
                      <% end %>
                      Votes <span class="ml-1"><%= @answer.votes.count %></span>
                      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-2 feather feather-message-square icon-md">
                        <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path>
                      </svg> Comments <%= @answer.comments.count %>
                    </p>
                  </div>
                  <hr>
                  <!-- Comment form -->
                  <%= render "comments/form" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <h3 class="pl-1">Comments</h3>
      <% @answer.comments.each do |comment|%>
        <div class="row">
          <div class="col-md-12 grid-margin">
            <div class="card rounded">
              <div class="card-header">
                <div class="d-flex align-items-center justify-content-between">
                  <div class="d-flex align-items-center">
                    <div class="ml-2">
                      <% if @current_user.id == comment.user_id %>
                        <%= form_with(model: @current_user.comments.find_by(id: comment.id), html: { method: :delete }, local: true) do |f| %>
                          <%= f.hidden_field :answer_id, value: comment.answer_id %>
                          <%= button_tag type: 'submit', class: "btn text-danger btn-icon", title: "UnFollow" do %>
                            <i class="fa fa-trash"></i>
                          <% end %>
                        <% end %>
                      <% end %>
                      <p><%= comment.user.name if comment.user %>
                      </p>
                      <p class="tx-11 text-muted"><%= time_ago_in_words(comment.created_at) if comment.created_at? %></p>
                    </div>
                  </div>
                </div>
                <div class="card-body">
                  <p class="mb-3 tx-14"><%= comment.title %></p>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <!-- middle wrapper end -->
    <%= render "answers/topics" %>
  </div>
</div>