config/routes.rb
Rails.application.routes.draw do
  get "question_categories/show"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :article_categories do
    resources :articles do
      resources :replies
      resources :likes, only: [:create, :destroy]
    end
  end

  resources :question_categories do
    resources :questions do
      resources :answers do
        resources :comments, only: [:create, :destroy]
        resources :votes, only: [:create, :destroy]
      end
    end
  end

  resources :sessions, only: [:create]
  resources :questions do
    resources :answers do
      resources :comments, only: [:create, :destroy]
      resources :votes, only: [:create, :destroy]
    end
  end

  resources :answers do
    resources :comments, only: [:create, :destroy]
    resources :votes, only: [:create, :destroy]
  end

  resources :votes, only: [:destroy]
  resources :comments, only: [:destroy]

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :articles do
    resources :replies
    resources :likes, only: [:create, :destroy]
  end

  resources :likes, only: [:create, :destroy]

  resources :relationships, only: [:create, :destroy]
  resources :user_article_relationships, only: [:create, :destroy]
  resources :user_question_relations, only: [:create, :destroy]
  delete :logout, to: "sessions#logout"
  get :logged_in, to: "sessions#logged_in"
  root to: "static#index"

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :article_categories do
        resources :articles do
          resources :replies
          resources :likes, only: [:create, :destroy]
        end
      end

      resources :question_categories do
        resources :questions do
          resources :answers do
            resources :comments, only: [:create, :destroy]
            resources :votes, only: [:create, :destroy]
          end
        end
      end
      resources :sessions, only: [:create]
      resources :questions do
        resources :answers do
          resources :comments
          resources :votes, only: [:create, :destroy]
        end
      end

      resources :answers do
        resources :comments
        resources :votes, only: [:create, :destroy]
      end

      resources :users do
        member do
          get :following, :followers
        end
      end

      resources :articles do
        resources :replies
        resources :likes, only: [:create, :destroy]
      end
      resources :registrations, only: [:create]
      resources :relationships, only: [:create, :destroy]
      resources :user_article_relationships, only: [:create, :destroy]
      resources :user_question_relations, only: [:create, :destroy]
      delete :logout, to: "sessions#logout"
      get :logged_in, to: "sessions#logged_in"
      root to: "static#home"
    end
  end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
  <%= link_to 'Sosho', root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item"><%= link_to 'Home', root_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to 'News', articles_path, class: "nav-link"  %></li>
      <li class="nav-item"><%= link_to 'QA', answers_path, class: "nav-link"  %></li>
      <% if !@current_user %>
        <li class="nav-item"><%= link_to 'Sign up', new_user_path, class: "nav-link"  %></li>
        <li class="nav-item"><%= link_to 'Sign in', login_path, class: "nav-link"  %></li>
      <% else %>
        <li class="text-light"><%= link_to @current_user.name, @current_user, class: "nav-link"  %></li>
        <li><%= link_to "Log out", logout_path, method: :delete, class: "nav-link"  %></li>
      <% end %>
    </ul>
    <% if @current_user %>
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
        Ask Question
      </button>
    <% end %>
  </div>
</nav>
<%= render "questions/form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HekaniSocialMedia</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <div class="container-fluid">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-warning alert-dismissible fade show alert-<%= message_type %>" role="alert">
          <%= message %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
      <%= render("layouts/header") %>
      <%= yield %>
    </div>
  </body>
</html>